export const languages = [
  { code: "en", label: "English", short: "EN" },
  { code: "zh", label: "中文", short: "中文" },
  { code: "nl", label: "Nederlands", short: "NL" },
];

export const defaultLang = "en";

export const ui = {
  en: {
    siteName: "CSMN",
    siteLongName: "Chinese Student Ministries Netherlands",
    nav: {
      home: "@CSMN",
      events: "Events",
      fellowship: "Fellowship",
      resources: "Resources",
      videos: "Songs & videos",
      about: "About Us",
      login: "Login",
      donate: "Make a donation to CSMN",
      search: "Search",
      menu: "Menu",
      close: "Close",
      language: "Language",
    },
    pages: {
      home: "Home",
      events: "Events",
      fellowship: "Fellowship",
      "discover-life": "Discover Life",
      resources: "Resources",
      "chinese-recipes": "Chinese recipes",
      "bible-study-and-research": "Bible study & research",
      "topical-studies": "Topical Studies",
      "spiritual-growth": "Spiritual growth",
      videos: "Songs & videos",
      about: "About Us",
      faq: "FAQ",
      nijmegen: "CSMN Nijmegen",
      anbi: "ANBI",
      donate: "Donate",
      search: "Search",
    },
    home: {
      heroTitle: "Events",
      heroText: "Join us at the CSMN events, a vibrant space where we come together to connect, share, and grow as a community.",
      heroCta: "Read More",
      introTitle: "Events",
      introText: "We organize gatherings where you can hang out. Check the events below and sign up when you want to join.",
      discoverTitle: "Discover life with Head, Heart and Hands",
      discoverText: "Chinese Student Ministries Netherlands (CSMN) is a place where Chinese university students in the Netherlands can meet, learn about Dutch culture, and explore Christianity. All Chinese students are welcome, regardless of their faith or worldview.",
      readMore: "Read more",
    },
    cards: {
      connect: {
        title: "Connect",
        text: "Chat about daily life in the Netherlands, enjoy a meal, and encourage each other in your spiritual journey.",
      },
      media: {
        title: "Songs & videos",
        text: "A curated selection of songs, movies, and talks to inspire, encourage, and support you.",
      },
      resources: {
        title: "Resources",
        text: "Materials to help you learn with your head and heart, with space for honest questions.",
      },
    },
    media: {
      videoType: "Video",
      searchLabel: "Search videos",
      searchPlaceholder: "Search title, description, or extra terms...",
      collectionFilter: "Filter by collection",
      tagFilter: "Filter by tag",
      allCollections: "All collections",
      allTags: "All tags",
      resetFilters: "Reset filters",
      resultSingular: "item",
      resultPlural: "items",
      noResults: "No matching items yet.",
      watch: "Watch",
      tags: "Tags",
      submittedBy: "Submitted by",
      published: "Published",
      backToVideos: "Back to songs & videos",
      videoCatalogTitle: "Songs & videos",
      videoCatalogIntro: "Search talks, testimonies, music videos, worship songs, and other media shared by CSMN editors.",
    },
    search: {
      title: "Search CSMN",
      placeholder: "Search songs & videos, pages, topics...",
      results: "results",
      noResults: "No results found.",
      pageType: "Page",
      videoType: "Video",
    },
    footer: {
      contact: "Contact",
      copyright: "© 2026 CSMN",
    },
  },
  zh: {
    siteName: "CSMN",
    siteLongName: "荷兰中国学生事工",
    nav: {
      home: "@CSMN",
      events: "活动",
      fellowship: "团契",
      resources: "资源",
      videos: "诗歌与视频",
      about: "关于我们",
      login: "登录",
      donate: "奉献支持 CSMN",
      search: "搜索",
      menu: "菜单",
      close: "关闭",
      language: "语言",
    },
    pages: {
      home: "首页",
      events: "活动",
      fellowship: "团契",
      "discover-life": "探索生命",
      resources: "资源",
      "chinese-recipes": "中国菜谱",
      "bible-study-and-research": "圣经学习与研究",
      "topical-studies": "Topical Studies",
      "spiritual-growth": "灵命成长",
      videos: "诗歌与视频",
      about: "关于我们",
      faq: "常见问题",
      nijmegen: "CSMN 奈梅亨",
      anbi: "ANBI",
      donate: "奉献",
      search: "搜索",
    },
    home: {
      heroTitle: "活动",
      heroText: "欢迎参加 CSMN 活动，在充满活力的空间中相聚、交流、分享，并在群体中成长。",
      heroCta: "了解更多",
      introTitle: "活动",
      introText: "我们定期组织活动，例如聚餐、徒步旅行、城市旅行和电影之夜。请查看下面的活动，并在想参加时报名。",
      discoverTitle: "用头脑、心灵和双手探索生命",
      discoverText: "华人学生团契是一个独特的平台，让中国大学生可以聚会、了解荷兰文化和基督信仰。我们尊重你的宗教观和世界观，并欢迎所有中国学生。每周中式晚餐后，学生们会思考一些有意义的人生问题，并以圣经作为引导。",
      readMore: "了解更多",
    },
    cards: {
      connect: {
        title: "连接",
        text: "分享在荷兰的日常生活，一起吃饭，并在属灵旅程中彼此鼓励。",
      },
      media: {
        title: "诗歌与视频",
        text: "精选诗歌、影片和讲座，带来启发、鼓励和支持。",
      },
      resources: {
        title: "资源",
        text: "帮助你用头脑和心灵学习，也给真实的问题留出空间。",
      },
    },
    media: {
      videoType: "视频",
      searchLabel: "搜索视频",
      searchPlaceholder: "搜索标题、描述或额外关键词……",
      collectionFilter: "按内容分类筛选",
      tagFilter: "按标签筛选",
      allCollections: "所有分类",
      allTags: "所有标签",
      resetFilters: "重置筛选",
      resultSingular: "项",
      resultPlural: "项",
      noResults: "暂时没有匹配的内容。",
      watch: "观看",
      tags: "标签",
      submittedBy: "上传者",
      published: "发布日期",
      backToVideos: "返回诗歌与视频",
      videoCatalogTitle: "诗歌与视频",
      videoCatalogIntro: "搜索 CSMN 编辑分享的讲座、见证、音乐视频、敬拜诗歌和其他媒体。",
    },
    search: {
      title: "搜索 CSMN",
      placeholder: "搜索诗歌与视频、页面、主题……",
      results: "个结果",
      noResults: "没有找到结果。",
      pageType: "页面",
      videoType: "视频",
    },
    footer: {
      contact: "联系",
      copyright: "© 2026 CSMN",
    },
  },
  nl: {
    siteName: "CSMN",
    siteLongName: "Chinese Student Ministries Netherlands",
    nav: {
      home: "@CSMN",
      events: "Events",
      fellowship: "Fellowship",
      resources: "Resources",
      videos: "Liederen & video's",
      about: "Over Ons",
      login: "Login",
      donate: "Doneer aan CSMN",
      search: "Zoeken",
      menu: "Menu",
      close: "Sluiten",
      language: "Taal",
    },
    pages: {
      home: "Home",
      events: "Events",
      fellowship: "Fellowship",
      "discover-life": "Discover Life",
      resources: "Resources",
      "chinese-recipes": "Chinese recepten",
      "bible-study-and-research": "Bijbelstudie & onderzoek",
      "topical-studies": "Topical Studies",
      "spiritual-growth": "Geestelijke groei",
      videos: "Liederen & video's",
      about: "Over Ons",
      faq: "Veelgestelde vragen",
      nijmegen: "CSMN Nijmegen",
      anbi: "ANBI",
      donate: "Doneren",
      search: "Zoeken",
    },
    home: {
      heroTitle: "Events",
      heroText: "Doe mee met de CSMN-events: een levendige plek waar we samenkomen om contact te maken, te delen en als gemeenschap te groeien.",
      heroCta: "Lees meer",
      introTitle: "Events",
      introText: "We organiseren regelmatig activiteiten, zoals gezamenlijke maaltijden, wandelingen, stadsuitjes en filmavonden. Bekijk de events hieronder en meld je aan wanneer je wilt meedoen.",
      discoverTitle: "Discover life met hoofd, hart en handen",
      discoverText: "Chinese Student Ministries Netherlands (CSMN) is een plek waar Chinese studenten aan Nederlandse universiteiten elkaar kunnen ontmoeten, meer kunnen leren over de Nederlandse cultuur en het christelijk geloof. Alle Chinese studenten zijn welkom, ongeacht hun geloofsovertuiging of levensbeschouwing. Elke week, na een Chinese maaltijd, gaan studenten in op betekenisvolle levensvragen en gebruiken ze de Bijbel als leidraad.",
      readMore: "Lees meer",
    },
    cards: {
      connect: {
        title: "Connect",
        text: "Praat over het dagelijks leven in Nederland, eet samen en moedig elkaar aan.",
      },
      media: {
        title: "Liederen & video's",
        text: "Een selectie van liederen, films en talks om je te inspireren en ondersteunen.",
      },
      resources: {
        title: "Resources",
        text: "Materiaal om te leren met hoofd en hart, met ruimte voor eerlijke vragen.",
      },
    },
    media: {
      videoType: "Video",
      searchLabel: "Zoek video's",
      searchPlaceholder: "Zoek op titel, beschrijving of extra termen...",
      collectionFilter: "Filter op collectie",
      tagFilter: "Filter op tag",
      allCollections: "Alle collecties",
      allTags: "Alle tags",
      resetFilters: "Filters wissen",
      resultSingular: "item",
      resultPlural: "items",
      noResults: "Geen overeenkomende items gevonden.",
      watch: "Kijken",
      tags: "Tags",
      submittedBy: "Toegevoegd door",
      published: "Gepubliceerd",
      backToVideos: "Terug naar liederen & video's",
      videoCatalogTitle: "Liederen & video's",
      videoCatalogIntro: "Zoek talks, getuigenissen, muziekvideo's, aanbiddingsliederen en andere media van CSMN.",
    },
    search: {
      title: "Zoeken in CSMN",
      placeholder: "Zoek liederen & video's, pagina's en onderwerpen...",
      results: "resultaten",
      noResults: "Geen resultaten gevonden.",
      pageType: "Pagina",
      videoType: "Video",
    },
    footer: {
      contact: "Contact",
      copyright: "© 2026 CSMN",
    },
  },
};

export function getUi(lang) {
  return ui[lang] || ui[defaultLang];
}
