export const languages = [
  { code: "en", label: "English", short: "EN" },
  { code: "zh", label: "中文", short: "中文" },
  { code: "nl", label: "Nederlands", short: "NL" },
];

export const defaultLang = "en";

export const ui = {
  en: {
    siteName: "CSMN",
    siteLongName: "Chinese Student Ministry Netherlands",
    nav: {
      home: "@CSMN",
      events: "Events",
      fellowship: "Fellowship",
      resources: "Resources",
      songs: "Songs",
      videos: "Videos",
      about: "About Us",
      login: "Login",
      donate: "Make a donation to CSMN",
      search: "Search",
      menu: "Menu",
      close: "Close",
      language: "Language",
    },
    pages: {
      home: "Home",
      events: "Events",
      fellowship: "Fellowship",
      "discover-life": "Discover Life",
      resources: "Resources",
      videos: "Videos",
      songs: "Songs",
      about: "About Us",
      donate: "Donate",
      search: "Search",
    },
    home: {
      heroTitle: "Events",
      heroText: "Join us at CSMN events, a warm space to connect, share, and grow as a community.",
      heroCta: "Read More",
      introTitle: "Events",
      introText: "We organize gatherings for you to hang out. Check the events below and sign up when you want to join.",
      discoverTitle: "Discover life with Head, Heart and Hands",
      discoverText: "CSMN is a place where Chinese university students in the Netherlands can meet, learn about Dutch culture, and explore Christianity.",
      readMore: "Read more",
    },
    cards: {
      connect: {
        title: "Connect",
        text: "Chat about daily life in the Netherlands, enjoy a meal, and encourage each other in your spiritual journey.",
      },
      media: {
        title: "Songs & Video",
        text: "A curated selection of songs, movies, and talks to inspire, encourage, and support you.",
      },
      resources: {
        title: "Resources",
        text: "Material to help you learn by head and heart, with space for honest questions.",
      },
    },
    media: {
      all: "All",
      allTypes: "All types",
      allLanguages: "All languages",
      videosOnly: "Videos",
      songsOnly: "Songs",
      videoType: "Video",
      songType: "Song",
      yes: "Yes",
      no: "No",
      searchPlaceholder: "Search title, artist, topic, language...",
      filterType: "Type",
      filterLanguage: "Language",
      noResults: "No matching items yet.",
      open: "Open",
      watch: "Watch",
      stream: "Stream",
      lyricsInVideo: "Lyrics in video",
      lyricsLanguage: "Lyrics language",
      audio: "Audio",
      artist: "Artist",
      category: "Category",
      tags: "Tags",
      submittedBy: "Submitted by",
      published: "Published",
      backToVideos: "Back to videos",
      backToSongs: "Back to songs",
      videoCatalogTitle: "Videos",
      videoCatalogIntro: "Search talks, testimonies, music videos, and other media shared by CSMN editors.",
      songCatalogTitle: "Songs & Streaming",
      songCatalogIntro: "Search songs, check lyrics availability, and stream directly from the source.",
    },
    search: {
      title: "Search CSMN",
      placeholder: "Search videos, songs, pages, topics...",
      results: "results",
      noResults: "No results found.",
      pageType: "Page",
      videoType: "Video",
      songType: "Song",
    },
    footer: {
      contact: "Contact",
      copyright: "© 2026 CSMN",
    },
  },
  zh: {
    siteName: "CSMN",
    siteLongName: "荷兰中国学生事工",
    nav: {
      home: "@CSMN",
      events: "活动",
      fellowship: "团契",
      resources: "资源",
      songs: "诗歌",
      videos: "视频",
      about: "关于我们",
      login: "登录",
      donate: "奉献支持 CSMN",
      search: "搜索",
      menu: "菜单",
      close: "关闭",
      language: "语言",
    },
    pages: {
      home: "首页",
      events: "活动",
      fellowship: "团契",
      "discover-life": "探索生命",
      resources: "资源",
      videos: "视频",
      songs: "诗歌",
      about: "关于我们",
      donate: "奉献",
      search: "搜索",
    },
    home: {
      heroTitle: "活动",
      heroText: "欢迎参加 CSMN 活动，一起交流、分享，并在群体中成长。",
      heroCta: "了解更多",
      introTitle: "活动",
      introText: "我们组织聚会和活动。请查看下面的活动，并在想参加时注册。",
      discoverTitle: "用头脑、心灵和双手探索生命",
      discoverText: "CSMN 是在荷兰的中国学生相聚、了解荷兰文化并探索基督信仰的地方。",
      readMore: "了解更多",
    },
    cards: {
      connect: {
        title: "连接",
        text: "分享在荷兰的日常生活，一起吃饭，并在属灵旅程中彼此鼓励。",
      },
      media: {
        title: "诗歌与视频",
        text: "精选诗歌、影片和讲座，带来启发、鼓励和支持。",
      },
      resources: {
        title: "资源",
        text: "帮助你用头脑和心灵学习，也给真实的问题留出空间。",
      },
    },
    media: {
      all: "全部",
      allTypes: "全部类型",
      allLanguages: "全部语言",
      videosOnly: "视频",
      songsOnly: "诗歌",
      videoType: "视频",
      songType: "诗歌",
      yes: "是",
      no: "否",
      searchPlaceholder: "搜索标题、歌手、主题、语言……",
      filterType: "类型",
      filterLanguage: "语言",
      noResults: "暂时没有匹配的内容。",
      open: "打开",
      watch: "观看",
      stream: "播放",
      lyricsInVideo: "视频中有歌词",
      lyricsLanguage: "歌词语言",
      audio: "音频",
      artist: "歌手",
      category: "分类",
      tags: "标签",
      submittedBy: "上传者",
      published: "发布日期",
      backToVideos: "返回视频",
      backToSongs: "返回诗歌",
      videoCatalogTitle: "视频",
      videoCatalogIntro: "搜索 CSMN 编辑分享的讲座、见证、音乐视频和其他媒体。",
      songCatalogTitle: "诗歌与播放",
      songCatalogIntro: "搜索诗歌，查看歌词信息，并直接打开播放来源。",
    },
    search: {
      title: "搜索 CSMN",
      placeholder: "搜索视频、诗歌、页面、主题……",
      results: "个结果",
      noResults: "没有找到结果。",
      pageType: "页面",
      videoType: "视频",
      songType: "诗歌",
    },
    footer: {
      contact: "联系",
      copyright: "© 2026 CSMN",
    },
  },
  nl: {
    siteName: "CSMN",
    siteLongName: "Chinese Student Ministry Netherlands",
    nav: {
      home: "@CSMN",
      events: "Events",
      fellowship: "Fellowship",
      resources: "Resources",
      songs: "Liederen",
      videos: "Video's",
      about: "Over Ons",
      login: "Login",
      donate: "Doneer aan CSMN",
      search: "Zoeken",
      menu: "Menu",
      close: "Sluiten",
      language: "Taal",
    },
    pages: {
      home: "Home",
      events: "Events",
      fellowship: "Fellowship",
      "discover-life": "Discover Life",
      resources: "Resources",
      videos: "Video's",
      songs: "Liederen",
      about: "Over Ons",
      donate: "Doneren",
      search: "Zoeken",
    },
    home: {
      heroTitle: "Events",
      heroText: "Doe mee met CSMN-events: een warme plek om te verbinden, delen en groeien als community.",
      heroCta: "Lees meer",
      introTitle: "Events",
      introText: "We organiseren bijeenkomsten om elkaar te ontmoeten. Bekijk de events hieronder en meld je aan.",
      discoverTitle: "Discover life met hoofd, hart en handen",
      discoverText: "CSMN is een plek waar Chinese studenten in Nederland elkaar ontmoeten, cultuur leren kennen en het christelijk geloof verkennen.",
      readMore: "Lees meer",
    },
    cards: {
      connect: {
        title: "Connect",
        text: "Praat over het dagelijks leven in Nederland, eet samen en moedig elkaar aan.",
      },
      media: {
        title: "Liederen & Video",
        text: "Een selectie van liederen, films en talks om je te inspireren en ondersteunen.",
      },
      resources: {
        title: "Resources",
        text: "Materiaal om te leren met hoofd en hart, met ruimte voor eerlijke vragen.",
      },
    },
    media: {
      all: "Alles",
      allTypes: "Alle types",
      allLanguages: "Alle talen",
      videosOnly: "Video's",
      songsOnly: "Liederen",
      videoType: "Video",
      songType: "Lied",
      yes: "Ja",
      no: "Nee",
      searchPlaceholder: "Zoek op titel, artiest, onderwerp of taal...",
      filterType: "Type",
      filterLanguage: "Taal",
      noResults: "Geen overeenkomende items gevonden.",
      open: "Open",
      watch: "Kijken",
      stream: "Stream nu",
      lyricsInVideo: "Lyrics in video",
      lyricsLanguage: "Lyrics taal",
      audio: "Audio",
      artist: "Artiest",
      category: "Categorie",
      tags: "Tags",
      submittedBy: "Toegevoegd door",
      published: "Gepubliceerd",
      backToVideos: "Terug naar video's",
      backToSongs: "Terug naar liederen",
      videoCatalogTitle: "Video's",
      videoCatalogIntro: "Zoek talks, getuigenissen, muziekvideo's en andere media van CSMN.",
      songCatalogTitle: "Liederen & Streaming",
      songCatalogIntro: "Zoek liederen, controleer of lyrics aanwezig zijn en stream direct.",
    },
    search: {
      title: "Zoeken in CSMN",
      placeholder: "Zoek video's, liederen, pagina's en onderwerpen...",
      results: "resultaten",
      noResults: "Geen resultaten gevonden.",
      pageType: "Pagina",
      videoType: "Video",
      songType: "Lied",
    },
    footer: {
      contact: "Contact",
      copyright: "© 2026 CSMN",
    },
  },
};

export function getUi(lang) {
  return ui[lang] || ui[defaultLang];
}
